apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      containers:
        - name: whiteboard
          image: suryatejasanku/whiteboard-app:latest  # Replace with your Docker Hub image
          ports:
            - containerPort: 8000
