image:
  repository: suryatejasanku/whiteboard-new
  tag: latest

service:
  type: ClusterIP
  port: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

serviceAccount:
  create: false

ingress:
  enabled: false        # Change to true only if you want to use Ingress
  className: nginx
  annotations: {}
  hosts:
    - host: whiteboard.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
