image:
  repository: suryatejasanku/whiteboard-new
  tag: latest
 
 service:
  port: 8000
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75
