image:
  repository: suryatejasanku/whiteboard-new
  tag: latest

service:
  type: ClusterIP
  port: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

ingress:
  enabled: false   # Set to true if you're using ingress
  className: nginx
  annotations: {}
  hosts:
    - host: whiteboard.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: false
