name: CI/CD Pipeline for Whiteboard

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: suryatejasanku/whiteboard-app:latest

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Update Helm chart with new image tag
      run: sed -i "s|tag:.*|tag: latest|" charts/whiteboard/values.yaml

        git add helm/values.yaml
        git commit -m "CI: Update image tag to latest" || echo "No changes to commit"
        git push origin main
